.gitattributes, CHANGES.md, Makefile, gdm/cli.py, gdm/commands.py, gdm/common.py, gdm/config.py, gdm/shell.py, gdm/test/test_all.py, gdm/test/test_cli.py, gdm/test/test_config.py, gdm/test/test_shell.py
=> Add '--force' argument to overwrite dependencies

CHANGES.md, README.md, gdm/__init__.py, gdm/cli.py, gdm/commands.py, gdm/config.py, gdm/shell.py, gdm/test/test_cli.py, gdm/test/test_commands.py, gdm/test/test_config.py, gdm/test/test_shell.py
=> Replace checkout with reset

gdm/commands.py, gdm/common.py, gdm/config.py, gdm/shell.py
=> Disable printing if '--quiet'

CHANGES.md, Makefile, gdm/__init__.py, gdm/cli.py, gdm/commands.py, gdm/config.py, gdm/shell.py, gdm/test/conftest.py, gdm/test/test_cli.py, gdm/test/test_config.py, gdm/test/test_shell.py, scent.py, tests/conftest.py, tests/test_all.py
=> Add option to disable cleaning untracked files

CHANGES.md, Makefile, README.md, gdm/__init__.py, gdm/shell.py, gdm/test/files/gdm.yml, gdm/test/test_config.py, gdm/test/test_shell.py, tests/files/gdm.yml
=> Support rev-parse checkout

CHANGES.md, gdm/__init__.py, gdm/cli.py, gdm/plugin.py, gdm/test/test_cli.py, gdm/test/test_plugin.py
=> Make '--no-clean' the default

.pep257, CHANGES.md, Makefile, gdm/__init__.py, gdm/cli.py, gdm/commands.py, gdm/common.py, gdm/config.py, gdm/plugin.py, gdm/shell.py, gdm/test/test_cli.py, gdm/test/test_plugin.py
=> Add recursive option to 'update'

CHANGES.md, Makefile, gdm/__init__.py, gdm/config.py, gdm/test/test_config.py, tests/test_all.py
=> Hotfix v0.4.2

CHANGES.md, gdm/__init__.py, gdm/cli.py, gdm/commands.py, gdm/plugin.py, gdm/test/test_cli.py, gdm/test/test_plugin.py
=> Add '--no-lock' option to 'update' command

CHANGES.md, docs/interfaces/api.md, docs/interfaces/cli.md, gdm/__init__.py, gdm/cli.py, gdm/commands.py, gdm/common.py, gdm/config.py, gdm/plugin.py, gdm/settings.py, gdm/shell.py, gdm/test/test_cli.py, gdm/test/test_commands.py, gdm/test/test_common.py, gdm/test/test_config.py, gdm/test/test_plugin.py, tests/test_all.py
=> Support installing/updating specific dependencies

CHANGES.md, docs/interfaces/api.md, gdm/cli.py, gdm/commands.py, gdm/common.py, gdm/config.py, gdm/plugin.py, gdm/test/test_cli.py, gdm/test/test_config.py, gdm/test/test_plugin.py
=> Add '--depth' option to install/update/list

CHANGES.md, Makefile, gdm/__init__.py, gdm/commands.py, gdm/config.py, gdm/test/test_config.py
=> Apply dependency filter to locking

CHANGES.md, docs/interfaces/api.md, docs/interfaces/cli.md, gdm/__init__.py, gdm/cli.py, gdm/commands.py, gdm/test/test_cli.py, tests/test_api.py
=> Make locking explicit

gdm/shell.py, gdm/test/test_shell.py
=> Clone from a local repo cache

CHANGES.md, docs/interfaces/api.md, docs/interfaces/cli.md, gdm/__init__.py, gdm/cli.py, gdm/commands.py, gdm/config.py, gdm/plugin.py, gdm/shell.py, gdm/test/test_cli.py, gdm/test/test_plugin.py, gdm/test/test_shell.py
=> Only fetch when updating or if a revision is missing

CHANGES.md, gdm/__init__.py, gdm/config.py, gdm/git.py, gdm/shell.py, gdm/source.py, gdm/test/__init__.py, gdm/test/test_git.py, gdm/test/test_shell.py
=> Refactor shell mixins

gdm/common.py, gdm/exceptions.py, gdm/git.py, gdm/shell.py, gdm/source.py, gdm/test/test_git.py, gdm/test/test_shell.py, tests/test_api.py
=> Fail when locking invalid repositories

CHANGES.md, Makefile, docs/interfaces/cli.md, gdm/__main__.py, gdm/cli.py, gdm/commands.py, gdm/system.py, scent.py, tests/test_cli.py, tests/test_main.py
=> Add 'edit' command

CHANGES.md, gitman/cli.py, gitman/test/test_cli.py
=> Default depth to 5

CHANGELOG.md, README.md, docs/index.md, docs/use-cases/branch-tracking.md, docs/use-cases/build-integration.md, docs/use-cases/linked-features.md, docs/use-cases/submodules.md, gitman/__init__.py, gitman/models/config.py, gitman/models/source.py, gitman/shell.py, gitman/test/files/gdm-custom.yml, gitman/test/files/gdm-default.yml, gitman/test/files/gitman.yml, gitman/test/test_models_source.py, gitman/test/test_shell.py, tests/files/gdm.yml, tests/test_api.py
=> Rename config keys

docs/use-cases/build-integration.md, gitman/models/config.py, gitman/test/test_models_config.py, tests/test_api.py
=> Rename the default location to 'gitman_sources'

CHANGELOG.md, gitman/__init__.py, gitman/cli.py, gitman/commands.py, gitman/common.py, gitman/git.py, gitman/models/source.py, gitman/shell.py, tests/test_cli.py
=> Add color to the output

gitman/models/source.py, setup.py, tests/test_api.py
=> Never lock a dirty version

.appveyor.yml, CHANGELOG.md, gitman/models/config.py, gitman/models/source.py, gitman/tests/test_models_config.py, tests/test_api.py
=> Finalize Windows support

CHANGELOG.md, Makefile, README.md, docs/interfaces/api.md, docs/interfaces/cli.md, gitman/__init__.py, gitman/cli.py, gitman/commands.py, gitman/common.py, gitman/models/config.py, gitman/models/source.py, gitman/tests/test_cli.py, tests/test_api.py
=> Add 'init' command

.pylint.ini, CHANGELOG.md, Makefile, README.md, docs/interfaces/api.md, docs/interfaces/cli.md, docs/interfaces/plugin.md, gitman.yml, gitman/__init__.py, gitman/cli.py, gitman/commands.py, gitman/common.py, gitman/exceptions.py, gitman/git.py, gitman/models/config.py, gitman/models/source.py, gitman/plugin.py, gitman/shell.py, gitman/tests/test_cli.py, gitman/tests/test_common.py, gitman/tests/test_git.py, gitman/tests/test_shell.py, scent.py, tests/test_api.py
=> Support post-install scripts

CHANGELOG.md, gitman/__init__.py, gitman/cli.py, gitman/commands.py, gitman/common.py, gitman/exceptions.py, gitman/models/config.py, gitman/models/source.py, gitman/tests/test_commands.py, gitman/tests/test_models_config.py
=> Search for config files in the current directory up to the root

docs/setup/environment.md, gitman/git.py, gitman/settings.py, mkdocs.yml
=> Customize cache directory

CHANGELOG.md, docs/interfaces/api.md, docs/interfaces/cli.md, docs/interfaces/plugin.md, gitman/__init__.py, gitman/cli.py, gitman/commands.py, gitman/plugin.py, gitman/tests/test_cli.py, gitman/tests/test_plugin.py
Response to https://github.com/jacebrowning/gitman/pull/168#issuecomment-399792475
=> Remove confusing '--lock' option on 'update' command

docs/setup/environment.md, gitman/git.py, gitman/settings.py, gitman/tests/test_git.py
Implementation according to #178
=> Basic implementation to disable gitcache by set environment variable GITMAN_CACHE_DISABLE

docs/interfaces/api.md, docs/interfaces/cli.md, gitman/cli.py, gitman/commands.py, gitman/models/config.py, gitman/models/source.py, gitman/plugin.py, gitman/tests/test_cli.py, gitman/tests/test_plugin.py
Initial implementation related to #181
=> Initial implementation of --skip-changes option

CHANGELOG.md
Added skip-changes option note to changelog
=> Added skip-changes note to changelog

gitman/git.py
Normalize case and path before comparing paths in git.valid()
Issue:
See issue #233
=> Description:

gitman/cli.py, gitman/commands.py, gitman/tests/test_cli.py
=> Preserve root when uninstalling the same location

gitman/git.py
Fixes #218. Using the implementation suggested by @kevinv92
=> Fix sparse path handling

CHANGELOG.md, pyproject.toml
=> Bump version to 3.1

CHANGELOG.md, gitman/commands.py, gitman/models/__init__.py, gitman/models/config.py, gitman/tests/test_models_config.py, poetry.lock, pyproject.toml, pytest.ini, tests/test_api.py
=> Update dependency locator to include nested projects

CHANGELOG.md, docs/use-cases/default-groups.md, gitman/models/config.py, gitman/tests/test_models_config.py, pyproject.toml, tests/test_api.py
Contributes to https://github.com/jacebrowning/gitman/issues/284
=> Use the 'all' keyword to override the default group

.appveyor.yml, .github/workflows/main.yml, .tool-versions, CHANGELOG.md, Makefile, poetry.lock, pyproject.toml
Closes https://github.com/jacebrowning/gitman/issues/352
=> Bump version to 3.5.3
